apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-broken
  labels:
    app: nginx-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-broken
  template:
    metadata:
      labels:
        app: nginx-broken
    spec:
      containers:
      - name: nginx
        # DELIBERATE ERROR: 'nginx:1.404.0' does not exist
        image: nginx:1.404.0
        ports:
        - containerPort: 80